=== pkp/pkp-lib/dtd/countries.dtd
<!--
  * countries.dtd
  *
  * Copyright (c) 2000-2012 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for country lists.
  *
  * $Id$
  -->
<!ELEMENT countries (country+)>
<!ELEMENT country EMPTY>
	<!ATTLIST country
		code CDATA #REQUIRED
		name CDATA #REQUIRED>

=== pkp/pkp-lib/locale/uk_UA/countries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE countries SYSTEM "../../dtd/countries.dtd">
<!--
  * locale/uk_UA/countries.xml
  *
  * Copyright (c) 2013-2014 Simon Fraser University Library
  * Copyright (c) 2000-2014 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the uk_UA (Ukrainian) locale.
  *
  * Translated by Denys Solovianenko, 2010-2011
  * V. I. Vernadsky National Library of Ukraine
  -->

<countries>
	<country name="Афганістан" code="AF"/>
	<country name="Аландські острови" code="AX"/>
	<country name="Албанія" code="AL"/>
	<country name="Алжир" code="DZ"/>
	<country name="Американське Самоа" code="AS"/>
	<country name="Андорра" code="AD"/>
	<country name="Ангола" code="AO"/>
	<country name="Ангілья" code="AI"/>
	<country name="Антарктида" code="AQ"/>
	<country name="Антигуа і Барбуда" code="AG"/>
	<country name="Аргентина" code="AR"/>
	<country name="Вірменія" code="AM"/>
	<country name="Аруба" code="AW"/>
	<country name="Австралія" code="AU"/>
	<country name="Австрія" code="AT"/>
	<country name="Азербайджан" code="AZ"/>
	<country name="Багамські Острови" code="BS"/>
	<country name="Бахрейн" code="BH"/>
	<country name="Бангладеш" code="BD"/>
	<country name="Барбадос" code="BB"/>
	<country name="Білорусь" code="BY"/>
	<country name="Бельгія" code="BE"/>
	<country name="Беліз" code="BZ"/>
	<country name="Бенін" code="BJ"/>
	<country name="Бермудські острови" code="BM"/>
	<country name="Бутан" code="BT"/>
	<country name="Болівія" code="BO"/>
	<country name="Боснія і Герцеговина" code="BA"/>
	<country name="Ботсвана" code="BW"/>
	<country name="Острів Буве" code="BV"/>
	<country name="Бразилія" code="BR"/>
	<country name="Британська територія в Індійському океані" code="IO"/>
	<country name="Бруней" code="BN"/>
	<country name="Болгарія" code="BG"/>
	<country name="Буркіна-Фасо" code="BF"/>
	<country name="Бурунді" code="BI"/>
	<country name="Камбоджа" code="KH"/>
	<country name="Камерун" code="CM"/>
	<country name="Канада" code="CA"/>
	<country name="Кабо-Верде" code="CV"/>
	<country name="Кайманові острови" code="KY"/>
	<country name="Центрально-Африканська Республіка" code="CF"/>
	<country name="Чад" code="TD"/>
	<country name="Чилі" code="CL"/>
	<country name="КНР" code="CN"/>
	<country name="Острів Різдва" code="CX"/>
	<country name="Кокосові острови (Кілінг)" code="CC"/>
	<country name="Колумбія" code="CO"/>
	<country name="Коморські Острови" code="KM"/>
	<country name="Конго" code="CG"/>
	<country name="ДР Конго" code="CD"/>
	<country name="Острови Кука" code="CK"/>
	<country name="Коста-Рика" code="CR"/>
	<country name="Кот-д'Івуар" code="CI"/>
	<country name="Хорватія" code="HR"/>
	<country name="Куба" code="CU"/>
	<country name="Кіпр" code="CY"/>
	<country name="Чехія" code="CZ"/>
	<country name="Данія" code="DK"/>
	<country name="Джибуті" code="DJ"/>
	<country name="Домініка" code="DM"/>
	<country name="Домініканська Республіка" code="DO"/>
	<country name="Еквадор" code="EC"/>
	<country name="Єгипет" code="EG"/>
	<country name="Сальвадор" code="SV"/>
	<country name="Екваторіальна Гвінея" code="GQ"/>
	<country name="Еритрея" code="ER"/>
	<country name="Естонія" code="EE"/>
	<country name="Ефіопія" code="ET"/>
	<country name="Фолклендські (Мальвінські) острови" code="FK"/>
	<country name="Фарерські острови" code="FO"/>
	<country name="Фіджі" code="FJ"/>
	<country name="Фінляндія" code="FI"/>
	<country name="Франція" code="FR"/>
	<country name="Французька Гвіана" code="GF"/>
	<country name="Французька Полінезія" code="PF"/>
	<country name="Французькі Південні території" code="TF"/>
	<country name="Габон" code="GA"/>
	<country name="Гамбія" code="GM"/>
	<country name="Грузія" code="GE"/>
	<country name="Німеччина" code="DE"/>
	<country name="Гана" code="GH"/>
	<country name="Гібралтар" code="GI"/>
	<country name="Греція" code="GR"/>
	<country name="Ґренландія" code="GL"/>
	<country name="Гренада" code="GD"/>
	<country name="Гваделупа" code="GP"/>
	<country name="Гуам" code="GU"/>
	<country name="Гватемала" code="GT"/>
	<country name="Гвінея" code="GN"/>
	<country name="Гвінея-Бісау" code="GW"/>
	<country name="Гаяна" code="GY"/>
	<country name="Гаїті" code="HT"/>
	<country name="Острови Герд і Макдональд" code="HM"/>
	<country name="Ватикан" code="VA"/>
	<country name="Гондурас" code="HN"/> 
	<country name="Гонконг" code="HK"/>
	<country name="Угорщина" code="HU"/>
	<country name="Ісландія" code="IS"/>
	<country name="Індія" code="IN"/>
	<country name="Індонезія" code="ID"/>
	<country name="Іран" code="IR"/>
	<country name="Ірак" code="IQ"/>
	<country name="Ірландія" code="IE"/>
	<country name="Ізраїль" code="IL"/>
	<country name="Італія" code="IT"/>
	<country name="Ямайка" code="JM"/>
	<country name="Японія" code="JP"/>
	<country name="Йорданія" code="JO"/>
	<country name="Казахстан" code="KZ"/>
	<country name="Кенія" code="KE"/>
	<country name="Кірібаті" code="KI"/>
	<country name="КНДР" code="KP"/>
	<country name="Південна Корея" code="KR"/>
	<country name="Кувейт" code="KW"/>
	<country name="Киргизстан" code="KG"/>
	<country name="Лаос" code="LA"/>
	<country name="Латвія" code="LV"/>
	<country name="Ліван" code="LB"/>
	<country name="Лесото" code="LS"/>
	<country name="Ліберія" code="LR"/>
	<country name="Лівія" code="LY"/>
	<country name="Ліхтенштейн" code="LI"/>
	<country name="Литва" code="LT"/>
	<country name="Люксембург" code="LU"/>
	<country name="Макао" code="MO"/>
	<country name="Македонія" code="MK"/>
	<country name="Мадагаскар" code="MG"/>
	<country name="Малаві" code="MW"/>
	<country name="Малайзія" code="MY"/>
	<country name="Мальдіви" code="MV"/>
	<country name="Малі" code="ML"/>
	<country name="Мальта" code="MT"/>
	<country name="Маршаллові Острови" code="MH"/>
	<country name="Мартиніка" code="MQ"/>
	<country name="Мавританія" code="MR"/>
	<country name="Маврикій" code="MU"/>
	<country name="Майотта" code="YT"/>
	<country name="Мексика" code="MX"/>
	<country name="Федеративні Штати Мікронезії" code="FM"/>
	<country name="Молдова" code="MD"/>
	<country name="Монако" code="MC"/>
	<country name="Монголія" code="MN"/>
	<country name="Монтсеррат" code="MS"/>
	<country name="Марокко" code="MA"/>
	<country name="Мозамбік" code="MZ"/>
	<country name="М'янма" code="MM"/>
	<country name="Намібія" code="NA"/>
	<country name="Науру" code="NR"/>
	<country name="Непал" code="NP"/>
	<country name="Нідерланди" code="NL"/>
	<country name="Нідерландські Антильські острови" code="AN"/>
	<country name="Нова Каледонія" code="NC"/>
	<country name="Нова Зеландія" code="NZ"/>
	<country name="Нікарагуа" code="NI"/>
	<country name="Нігер" code="NE"/>
	<country name="Нігерія" code="NG"/>
	<country name="Ніуе" code="NU"/>
	<country name="Острів Норфолк" code="NF"/>
	<country name="Північні Маріанські острови" code="MP"/>
	<country name="Норвегія" code="NO"/>
	<country name="Оман" code="OM"/>
	<country name="Пакистан" code="PK"/>
	<country name="Палау" code="PW"/>
	<country name="Палестина" code="PS"/>
	<country name="Панама" code="PA"/>
	<country name="Папуа-Нова Гвінея" code="PG"/>
	<country name="Парагвай" code="PY"/>
	<country name="Перу" code="PE"/>
	<country name="Філіппіни" code="PH"/>
	<country name="Піткерн" code="PN"/>
	<country name="Польща" code="PL"/>
	<country name="Португалія" code="PT"/>
	<country name="Пуерто-Ріко" code="PR"/>
	<country name="Катар" code="QA"/>
	<country name="Реюньйон" code="RE"/>
	<country name="Румунія" code="RO"/>
	<country name="Російська Федерація" code="RU"/>
	<country name="Руанда" code="RW"/>
	<country name="Острів Святої Єлени" code="SH"/>
	<country name="Сент-Кітс і Невіс" code="KN"/>
	<country name="Сент-Люсія" code="LC"/>
	<country name="Сен-П'єр і Мікелон" code="PM"/>
	<country name="Сент-Вінсент і Гренадини" code="VC"/>
	<country name="Самоа" code="WS"/>
	<country name="Сан-Марино" code="SM"/>
	<country name="Сан-Томе і Принсіпі" code="ST"/>
	<country name="Саудівська Аравія" code="SA"/>
	<country name="Сенегал" code="SN"/>
	<country name="Сербія та Чорногорія" code="CS"/>
	<country name="Сейшельські Острови" code="SC"/>
	<country name="Сьєрра-Леоне" code="SL"/>
	<country name="Сингапур" code="SG"/>
	<country name="Словаччина" code="SK"/>
	<country name="Словенія" code="SI"/>
	<country name="Соломонові Острови" code="SB"/>
	<country name="Сомалі" code="SO"/>
	<country name="ПАР" code="ZA"/>
	<country name="Південна Джорджія та Південні Сандвічеві острови" code="GS"/>
	<country name="Іспанія" code="ES"/>
	<country name="Шрі-Ланка" code="LK"/>
	<country name="Судан" code="SD"/>
	<country name="Суринам" code="SR"/>
	<country name="Свальбард і Ян-Маєн" code="SJ"/>
	<country name="Свазіленд" code="SZ"/>
	<country name="Швеція" code="SE"/>
	<country name="Швейцарія" code="CH"/>
	<country name="Сирія" code="SY"/>
	<country name="Тайвань" code="TW"/>
	<country name="Таджикистан" code="TJ"/>
	<country name="Танзанія" code="TZ"/>
	<country name="Таїланд" code="TH"/>
	<country name="Східний Тимор" code="TL"/>
	<country name="Того" code="TG"/>
	<country name="Токелау" code="TK"/>
	<country name="Тонга" code="TO"/>
	<country name="Тринідад і Тобаго" code="TT"/>
	<country name="Туніс" code="TN"/>
	<country name="Туреччина" code="TR"/>
	<country name="Туркменістан" code="TM"/>
	<country name="Острови Теркс і Кайкос" code="TC"/>
	<country name="Тувалу" code="TV"/>
	<country name="Уганда" code="UG"/>
	<country name="Україна" code="UA"/>
	<country name="ОАЕ" code="AE"/>
	<country name="Велика Британія" code="GB"/>
	<country name="США" code="US"/>
	<country name="Дрібні віддалені острови США" code="UM"/>
	<country name="Уругвай" code="UY"/>
	<country name="Узбекистан" code="UZ"/>
	<country name="Вануату" code="VU"/>
	<country name="Венесуела" code="VE"/>
	<country name="В'єтнам" code="VN"/>
	<country name="Британські Віргінські острови" code="VG"/>
	<country name="Американські Віргінські острови" code="VI"/>
	<country name="Волліс і Футуна" code="WF"/>
	<country name="Західна Сахара" code="EH"/>
